// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC06bBLaJX3fHsAxgIL1kXbfeiWvgm2OhI',
    appId: '1:126649911612:android:981ffdfdd42bee88653639',
    messagingSenderId: '126649911612',
    projectId: 'fb-auth-bloc',
    storageBucket: 'fb-auth-bloc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAhG0VlOB1rQ8gsI03hIjeUexr8U-mgTI',
    appId: '1:126649911612:ios:7283457aa9ad88a9653639',
    messagingSenderId: '126649911612',
    projectId: 'fb-auth-bloc',
    storageBucket: 'fb-auth-bloc.appspot.com',
    iosClientId: '126649911612-daud01ql35vmjun3klq9qc2ep81ef0qj.apps.googleusercontent.com',
    iosBundleId: 'com.example.fbAuthBloc',
  );
}
